cloud-init modified and vars explanations added to AMI.md

diff --git a/cloud-init b/cloud-init
--- a/cloud-init
+++ b/cloud-init
@@ -28,6 +28,9 @@ if [ $? = 0 ]; then
     export CF_HELM_CHANNEL=dev
     echo "Exporting CF_HELM_CHANNEL"
   fi
+else
+  echo "Unable to read user-data file"
+  exit 1
 fi
 
 BRANCH=${BRANCH:-master}
